### ISSUE TITLE
Outline of Report

### ISSUE THREAD

**Issue by effat** [cleebp/group-g-feb1-report#1]
1) Possible Problem for (Copy-Paste) Experiment
     - Design Problems in Eclipse
     -Coding Problem in Eclipse

2) Participants of Experiment
    - Graduate level (CSC?) students/ undergrad level students. Participants are familiar to Java and the Eclipse IDE.

3) Time
     - 30 min~ 1 hr observation

4) Nature of Experiment
     - Multiple tasks can be given to one person (?)
     -Compare using clipboard between coding task vs design task

5) What to Measure from Experiment?
     - Correctness (?)
     -Completeness (?)

**Comment by cleebp** [comment]
It seems like this is all about an experiment, I thought we were leaning towards scrapping the experiment and just doing the lit review? Especially if we focus on the more thorough experiments already done in other literature I think this would be fine, what do you guys think?
